version: '2'
services:
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=kitodo
      - MYSQL_USER=kitodo
      - MYSQL_PASSWORD=kitodo
    volumes:
      - ./database:/var/lib/mysql
  main:
    build: .
    image: kitodo/production:2.x
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_ADDR=db
    volumes:
      - ./config:/usr/local/kitodo
    depends_on:
      - db
  
